# Generated by Django 2.0.2 on 2018-05-15 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_auto_20180305_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(blank=True, max_length=18)),
                ('real_name', models.CharField(blank=True, max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=11)),
                ('education', models.CharField(choices=[('university', '大学生'), ('senior', '中学生'), ('junior', '小学生')], default='university', max_length=10)),
                ('position', models.CharField(blank=True, max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('set_active', '更改用户成为不活跃状态'),),
            },
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
