# Generated by Django 2.0.2 on 2018-05-15 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_auto_20180515_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(blank=True, max_length=18)),
                ('real_name', models.CharField(blank=True, max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=11)),
                ('education', models.CharField(choices=[('university', '本科'), ('postgraduate', '研究生'), ('doctor', '博士')], default='university', max_length=10)),
                ('profession', models.CharField(blank=True, max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='position',
            new_name='profession',
        ),
    ]
