# Generated by Django 2.0.2 on 2018-05-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_testone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestOne',
        ),
    ]
