# Generated by Django 2.0.2 on 2018-05-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_unauditedcurriculum_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='file_name',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='img',
            field=models.FilePathField(default='/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculum',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='课程名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='path',
            field=models.FilePathField(default='/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='attachment',
            field=models.FilePathField(blank=True, null=True, verbose_name='附件'),
        ),
    ]
