# Generated by Django 2.0.2 on 2018-05-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_auto_20180520_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='img',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
