# Generated by Django 2.0.2 on 2018-04-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_auto_20180405_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='last_mod_time',
        ),
        migrations.AlterField(
            model_name='comment',
            name='curriculum',
            field=models.CharField(max_length=50),
        ),
    ]
