# Generated by Django 2.0.2 on 2018-05-15 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_auto_20180421_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': 'created_time', 'ordering': ['-created_time'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='curriculuminfo',
            options={'permissions': (('upload_file', '可以上传文件'), ('move_video', '移动视频所在库'))},
        ),
    ]
