# Generated by Django 2.0.2 on 2018-05-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_auto_20180516_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.BooleanField(default=True)),
            ],
        ),
    ]
