# Generated by Django 2.0.2 on 2018-05-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_delete_testone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculumparticipation',
            old_name='Series',
            new_name='series',
        ),
        migrations.AlterField(
            model_name='curriculumparticipation',
            name='curriculum',
            field=models.IntegerField(default=1),
        ),
    ]
