# Generated by Django 2.0.2 on 2018-05-18 03:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0008_delete_testone'),
    ]

    operations = [
        # migrations.RenameModel(
        #     old_name='PassCurriculum',
        #     new_name='Curriculum',
        # ),
        migrations.AlterModelOptions(
            name='unauditedcurriculum',
            options={'ordering': ['number'], 'permissions': (('upload_file', '可以上传文件'), ('move_video', '移动视频所在库'))},
        ),
        migrations.RenameField(
            model_name='curriculumparticipation',
            old_name='Series',
            new_name='series',
        ),
        migrations.AddField(
            model_name='series',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='标签，空格分割'),
        ),
        migrations.AlterField(
            model_name='curriculumparticipation',
            name='curriculum',
            field=models.IntegerField(default=1),
        ),
    ]
