# Generated by Django 2.0.2 on 2018-05-18 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0009_auto_20180518_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_name', models.CharField(max_length=50)),
                ('path', models.FilePathField()),
                ('number', models.IntegerField(verbose_name='集数')),
                ('attachment', models.FilePathField()),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Curriculum_editor', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Curriculum_owner', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Curriculum_series', to='curriculum.Series')),
            ],
        ),
        migrations.RemoveField(
            model_name='passcurriculum',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='passcurriculum',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='passcurriculum',
            name='series',
        ),
        migrations.DeleteModel(
            name='PassCurriculum',
        ),
    ]
