# Generated by Django 2.0.2 on 2018-05-18 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0010_auto_20180518_0329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculumparticipation',
            old_name='curriculum',
            new_name='curriculum_id',
        ),
    ]
