# Generated by Django 2.0.2 on 2018-05-18 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0011_auto_20180518_0331'),
    ]

    # operations = [
    #     migrations.RenameField(
    #         model_name='curriculumparticipation',
    #         old_name='curriculum_id',
    #         new_name='curriculum',
    #     ),
    # ]
